### PR TITLE
feat: add new vaults

### PR DESCRIPTION
**Pull request by Majorfi**
- Add missiing vaults in `main.c`
- Add new `yvUSDT` vault
- Add new `Balancer Boosted Aave USD Pool yVault` vault

### CODE REVIEW

**Comment by adrienlacombe-ledger** [comment]
@Majorfi few comments from the Donjon

- move the definitions into a separate file called contract.c https://github.com/LedgerHQ/app-plugin-yearn/blob/d924c3dde0b54fe132edee06e4b5837b3fd6270d/src/main.c#L27-L523
- add a comment when defining the function selector with its function signature for instance (do it for all)
```
static const uint8_t WITHDRAW_ALL_SELECTOR[SELECTOR_SIZE] = {0x3c, 0xcf, 0xd6, 0x0b}; // withdraw()
static const uint8_t WITHDRAW_SELECTOR[SELECTOR_SIZE] = {0x2e, 0x1a, 0x7d, 0x4d}; // withdraw(uint256 maxShares)
static const uint8_t WITHDRAW_TO_SELECTOR[SELECTOR_SIZE] = {0x00, 0xf7, 0x14, 0xce}; // withdraw(uint256 maxShares, address recipient)
static const uint8_t WITHDRAW_TO_SLIPPAGE_SELECTOR[SELECTOR_SIZE] = {0xe6, 0x36, 0x97, 0xc8}; // withdraw(uint256 maxShares, address recipient, uint256 maxLoss)
```
- add missing return statement https://github.com/LedgerHQ/app-plugin-yearn/blob/d924c3dde0b54fe132edee06e4b5837b3fd6270d/src/handle_init_contract.c#L29
- https://github.com/LedgerHQ/app-plugin-yearn/blob/d924c3dde0b54fe132edee06e4b5837b3fd6270d/src/handle_init_contract.c#L42-L47 `context->next_param = ZAP_TOKEN;` is being set for `WITHDRAW, WITHDRAW_TO, WITHDRAW_TO_SLIPPAGE and ZAP_IN` but it is only correct for `ZAP_IN` since for the others the next_param should be https://github.com/LedgerHQ/app-plugin-yearn/blob/d924c3dde0b54fe132edee06e4b5837b3fd6270d/src/handle_provide_parameter.c#L21 , https://github.com/LedgerHQ/app-plugin-yearn/blob/d924c3dde0b54fe132edee06e4b5837b3fd6270d/src/handle_provide_parameter.c#L33 , https://github.com/LedgerHQ/app-plugin-yearn/blob/d924c3dde0b54fe132edee06e4b5837b3fd6270d/src/handle_provide_parameter.c#L50
- regarding the `DEPOSIT, DEPOSIT_ALL`: https://github.com/LedgerHQ/app-plugin-yearn/blob/d924c3dde0b54fe132edee06e4b5837b3fd6270d/src/handle_provide_parameter.c#L3-L17 in case for deposit method we have 3 args and in case for deposit_all we have 2 args, with the current implementation it is possible to send more than 3 arguments and the logic is still correct. One solution could be to have two separate functions.
- regarding `WITHDRAW` this method only has one argument `uint256 maxShares`, https://github.com/LedgerHQ/app-plugin-yearn/blob/d924c3dde0b54fe132edee06e4b5837b3fd6270d/src/handle_provide_parameter.c#L19-L29 after reading the maxShares parameter set the `next_parameter` to `UNEXPECTED_PARAMETER` also since the first argument for `WITHDRAW, WITHDRAW_TO, WITHDRAW_TO_SLIPPAGE` is called `maxShares` replace `AMOUNT` with `MAXSHARES`
- https://github.com/LedgerHQ/app-plugin-yearn/blob/d924c3dde0b54fe132edee06e4b5837b3fd6270d/src/handle_provide_parameter.c#L116-L120 `handle_none` is actually just setting an error https://github.com/LedgerHQ/app-plugin-yearn/blob/d924c3dde0b54fe132edee06e4b5837b3fd6270d/src/handle_provide_parameter.c#L95 which will abort the signing process. And in these cases https://github.com/LedgerHQ/app-plugin-yearn/blob/d924c3dde0b54fe132edee06e4b5837b3fd6270d/src/handle_init_contract.c#L37-L41 the `next_param` is never actually set. Set it to `UNEXPECTED_PARAMETER` so that if any parameter is sent (should not happen because they do not have arguments) the `ethereum-app` will abort the signing process.
- it is possible that context->extra_address is never actually set https://github.com/LedgerHQ/app-plugin-yearn/blob/d924c3dde0b54fe132edee06e4b5837b3fd6270d/src/handle_provide_token.c#L11 for instance when calling the `deposits` methods.
- avoid code duplication when setting the `PLUGIN_NAME` set the `strlcpy` here https://github.com/LedgerHQ/app-plugin-yearn/blob/d924c3dde0b54fe132edee06e4b5837b3fd6270d/src/handle_query_contract_id.c#L7 and remove all the others `strlcpy`'s related with the `PLUGIN_NAME`
- use `size_t` instead of `uint8_t` https://github.com/LedgerHQ/app-plugin-yearn/blob/d924c3dde0b54fe132edee06e4b5837b3fd6270d/src/handle_query_contract_ui.c#L4-L10 , https://github.com/LedgerHQ/app-plugin-yearn/blob/d924c3dde0b54fe132edee06e4b5837b3fd6270d/src/handle_query_contract_ui.c#L13
- avoid using hard coded values, use `sizeof(tmp_buffer)` instead in https://github.com/LedgerHQ/app-plugin-yearn/blob/d924c3dde0b54fe132edee06e4b5837b3fd6270d/src/handle_query_contract_ui.c#L12

**Comment by adrienlacombe-ledger** [comment]
@saltyfacu few comments from the Donjon

- The arguments in https://github.com/yearn/app-plugin-yearn/blob/d98b04286ecb253d79e3c16ea0f87108f5430de2/src/contract.c#L3-L7 are wrong.
It should be
```
static const uint8_t DEPOSIT_SELECTOR[SELECTOR_SIZE] = {0x83,
                                                        0x40,
                                                        0xf5,
                                                        0x49};  // deposit(address vault, address partnerId, uint256 amount)
static const uint8_t DEPOSIT_ALL_SELECTOR[SELECTOR_SIZE] = {0xf9, 0x60, 0x9f, 0x08};   // deposit(address vault, address partnerId)
```

- There should be a test for each “selector” that targets all nano devices, for instance `DEPOSIT_ALL_SELECTOR` has no test and the `DEPOSIT_SELECTOR` https://github.com/yearn/app-plugin-yearn/blob/d98b04286ecb253d79e3c16ea0f87108f5430de2/tests/src/deposit_partner.test.js#L12 only target nano S (should also target nano nanoSP and nanoX )

- Please remove the following https://github.com/yearn/app-plugin-yearn/blob/d98b04286ecb253d79e3c16ea0f87108f5430de2/src/yearn_plugin.h#L67 since it is not necessary

- According to the comment https://github.com/yearn/app-plugin-yearn/blob/d98b04286ecb253d79e3c16ea0f87108f5430de2/src/handle_provide_parameter.c#L16-L17 if it is not necessary don’t copy the address just set the next parameter. Also in the `handle_deposit` https://github.com/yearn/app-plugin-yearn/blob/d98b04286ecb253d79e3c16ea0f87108f5430de2/src/handle_provide_parameter.c#L16-L17 remove those lines since it does not matter the `track_partner`

- Instead of calling `handle_none` delete this function and just set a plugin error in https://github.com/yearn/app-plugin-yearn/blob/d98b04286ecb253d79e3c16ea0f87108f5430de2/src/handle_provide_parameter.c#L9-L13

- All the `withdraw` selectors that have arguments have `maxShares` as first argument so rename `AMOUNT` to `MAXSHARES` to increase readability.

- Set a plugin error in https://github.com/yearn/app-plugin-yearn/blob/d98b04286ecb253d79e3c16ea0f87108f5430de2/src/handle_provide_parameter.c#L165 , https://github.com/yearn/app-plugin-yearn/blob/d98b04286ecb253d79e3c16ea0f87108f5430de2/src/handle_provide_parameter.c#L55 , https://github.com/yearn/app-plugin-yearn/blob/d98b04286ecb253d79e3c16ea0f87108f5430de2/src/handle_provide_parameter.c#L74 (or remove the `break` statement and add a comment with “fall through”, to increase readability, since no more parameters are expected.

- As before if its not needed just remove it https://github.com/yearn/app-plugin-yearn/blob/d98b04286ecb253d79e3c16ea0f87108f5430de2/src/handle_provide_parameter.c#L97

- Why is the following necessary https://github.com/yearn/app-plugin-yearn/blob/d98b04286ecb253d79e3c16ea0f87108f5430de2/src/handle_finalize.c#L10-L12

**Comment by saltyfacu** [comment]
> * The arguments in https://github.com/yearn/app-plugin-yearn/blob/d98b04286ecb253d79e3c16ea0f87108f5430de2/src/contract.c#L3-L7 are wrong.

Sorry, I was looking at another contract. Fixed.

> According to the comment https://github.com/yearn/app-plugin-yearn/blob/d98b04286ecb253d79e3c16ea0f87108f5430de2/src/handle_provide_parameter.c#L16-L17 if it is not necessary don’t copy the address just set the next parameter. Also in the handle_deposit https://github.com/yearn/app-plugin-yearn/blob/d98b04286ecb253d79e3c16ea0f87108f5430de2/src/handle_provide_parameter.c#L16-L17 remove those lines since it does not matter the track_partner

Done. I misunderstood the implementation, I thought I needed to move the pointer 20 bytes or 32 bytes depending if the param is an address or a uint256. But everything is working as expected after removing those :)

> All the withdraw selectors that have arguments have maxShares as first argument so rename AMOUNT to MAXSHARES to increase readability.

That's true, but we want to generalize the term AMOUNT, and use it for all amounts. We are still working on it.

> Instead of calling handle_none delete this function and just set a plugin error in https://github.com/yearn/app-plugin-yearn/blob/d98b04286ecb253d79e3c16ea0f87108f5430de2/src/handle_provide_parameter.c#L9-L13

We've put it there for readability and to be able to use it for future additions.

All other deletions were done. UNEXPECTED_PARAMETER cases fixed and added a comment where I kept it.

**Comment by adrienlacombe-ledger** [comment]
hi @saltyfacu only 2 comments ;)

- The following should be deleted https://github.com/yearn/app-plugin-yearn/blob/c7cc371a246d7c3bb39eb26b80b7af2f36a58095/src/handle_provide_parameter.c#L4 https://github.com/yearn/app-plugin-yearn/blob/c7cc371a246d7c3bb39eb26b80b7af2f36a58095/src/handle_provide_parameter.c#L98

- This logic does not seem correct, the way it works is that any number of 32byte parameters are sent to the plugin, the plugin either chooses to use each or not. So for instance in https://github.com/yearn/app-plugin-yearn/blob/c7cc371a246d7c3bb39eb26b80b7af2f36a58095/src/handle_provide_parameter.c#L9-L13 after the `vault` parameter the next parameter is always the `partner`. This can just be deleted since there is no interest in `TRACK_PARTNER`

**Comment by saltyfacu** [comment]
> * The following should be deleted https://github.com/yearn/app-plugin-yearn/blob/c7cc371a246d7c3bb39eb26b80b7af2f36a58095/src/handle_provide_parameter.c#L4 https://github.com/yearn/app-plugin-yearn/blob/c7cc371a246d7c3bb39eb26b80b7af2f36a58095/src/handle_provide_parameter.c#L98

Done

> This logic does not seem correct, the way it works is that any number of 32byte parameters are sent to the plugin, the plugin either chooses to use each or not. So for instance in https://github.com/yearn/app-plugin-yearn/blob/c7cc371a246d7c3bb39eb26b80b7af2f36a58095/src/handle_provide_parameter.c#L9-L13 after the vault parameter the next parameter is always the partner. This can just be deleted since there is no interest in TRACK_PARTNER

Great catch. Thanks. It was based on the previous descriptors that didn't use the partner's deposit contract. Also fixed.

**Comment by lpascal-ledger** [comment]
Hello @saltyfacu.
This PR is going to be merged&deployed on testing provider, but before that could you update the version number? 
Thanks

**Comment by saltyfacu** [comment]
Hello @lpascal-ledger ! Done

**Comment by lpascal-ledger** [comment]
Shouldn't have merged it on `main`. `main` is kept for production deployment, for now this code will lie on testing, so renamed the `main` into `develop` to keep track of this. `main` stays at commit 4bd22360a521a1bc52efd44744a87727b3172f74

**Pull request merged**
